import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Share",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className=" w-full md:w-1/2 mx-auto font-mono px-4 md:px-0">
          <nav className="flex justify-between md:items-center my-5 md:my-10 border-b border-b-gray-600 pb-3 ">
            <Link
              href={"/"}
              className=" text-4xl font-bold uppercase hover:scale-95 duration-300"
            >
              SimpleShare
            </Link>
            <Link
              href={"/posts/create"}
              className=" text-white bg-black font-medium text-2xl px-3 py-1 rounded-md active:scale-95 duration-200 w-fit"
            >
              +
            </Link>
          </nav>
          <div>{children}</div>
          <footer>
            <p className=" my-10 text-center font-medium text-lg text-gray-500">Copyright &#169; 2024 Christ</p>
          </footer>
        </section>
      </body>
    </html>
  );
}
